{% set version = "0.4.5" %}

package:
  name: pyct
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyct-core {{ version }}
    - pyyaml
    - requests

test:
  imports:
    - pyct
    - pyct.cmd

about:
  home: http://github.com/pyviz/pyct
  license: BSD-3-Clause
  license_family: BSD
  # in pyct-core
  # license_file: LICENSE.txt
  summary: 'Python package common tasks for users (e.g. copy examples, fetch data, ...)'
  doc_url: https://github.com/pyviz/pyct
  dev_url: https://github.com/pyviz/pyct

extra:
  recipe-maintainers:
    - ocefpaf
