{% set version = "0.5.0" %}

package:
  name: pyct
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyct/pyct-{{ version }}.tar.gz
  sha256: dd9f4ac5cbd8e37c352c04036062d3c5f67efec76d404761ef16b0cbf26aa6a0

build:
  entry_points:
    - pyct=pyct.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - param >=1.7.0
    - pip
  run:
    - python >={{ python_min }}
    - param >=1.7.0
    - setuptools >=61.0
    # cli
    - pyyaml
    - requests
  run_constrained:
    - pyct-core <0

test:
  imports:
    - pyct
    - pyct.cmd
  commands:
    - pip check
    - pyct --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/holoviz-dev/pyct
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python package common tasks for users (e.g. copy examples, fetch data, ...)
  doc_url: https://github.com/holoviz-dev/pyct#pyctbuild
  dev_url: https://github.com/holoviz-dev/pyct

extra:
  recipe-maintainers:
    - maximlt
    - ocefpaf
    - apmorton
